Add `deploy_with_id` method to `NetworkState`
dusk-network/rusk-vm pull request #211
Opened 2021-07-21 22:30 UTC by ZER0

Resolves: #210

2021-07-21 22:49 UTC, krl requested changes
strange utf-8 sneaked in, looks good otherwise

2021-07-21 22:49 UTC, krl commented on src/state.rs
> +    /// Returns a reference to the map of̦ registered host modules
is there some strange ligature here or why is this a diff? "f̦"

2021-07-21 23:00 UTC, krl approved these changes

2021-07-22 08:36 UTC, CPerezz reviewed
Should we really go towards that direction?

I don't really think so TBH. I think we should find a better way to manage the GENESIS_CONTRACT IDs TBH. Since we need to be very careful with this API.

2021-07-22 09:22 UTC, merged