Change ModuleConfig to be configurable by a file
dusk-network/rusk-vm pull request #226
Opened 2021-09-01 08:50 UTC by moCello

ModuleConfig used to get the configurations from the Schedule struct,
which had the hard-coded configurations. Schedule is now depricated
and ModuleConfig reads its configurations from a toml file.
This is to make the configurations of the VM more transparent and
adjusting them easier.
Also change the *InstrumentalizationError* to *InstrumentationError*.

Resolves: #221

2021-11-24 11:35 UTC, ureeves requested changes
Given these changes I think it would make sense to get rid of `NetworkState::new`. We can keep the `Default` since that would make a user think the default configuration is being used, but `new` seems misleading.

2021-11-24 11:54 UTC, miloszm commented
> Given these changes I think it would make sense to get rid of `NetworkState::new`. We can keep the `Default` since that would make a user think the default configuration is being used, but `new` seems misleading.

Agree - I also had doubts about it. Will make the appropriate change.

2021-11-24 13:24 UTC, miloszm commented
> > Given these changes I think it would make sense to get rid of `NetworkState::new`. We can keep the `Default` since that would make a user think the default configuration is being used, but `new` seems misleading.
> 
> Agree - I also had doubts about it. Will make the appropriate change.

Change is now done.

2021-11-24 15:04 UTC, ureeves requested changes
Some naming and type nits.

2021-11-24 16:36 UTC, miloszm commented on src/state.rs
> +        file_path: Option<String>,
Done

2021-11-24 16:36 UTC, miloszm commented on src/modules.rs
> +    pub fn from_file(file_path: Option<String>) -> Result<Self, VMError> {
Done

2021-12-01 16:26 UTC, ZER0 approved these changes
LGTM, just a minor nit.
But I was wondering if the `module_config` should now belong to `Contracts` struct instead of `NetworkState`.

2021-12-01 17:45 UTC, merged